### ISSUE TITLE
Provide additional extras

### ISSUE THREAD

**Issue by ekohl** [perdy/flama#18]
Currently there's the extra `full` which installs all dependencies. It would nice if I could choose just `apispec` and `pyyaml` with the correct versions. Would it be possible to provide all optional dependencies as extras?

**Comment by perdy** [comment]
Yes, it sounds reasonable to add small groups of dependencies to allow some features, such as `apispec` and `pyyaml` for schema and docs generation. I will check all combinations of dependencies and update the setup config.

Thanks !
