### ISSUE TITLE
Add to Starlette "Third Party Packages" docs?

### ISSUE THREAD

**Issue by tomchristie** [perdy/flama#24]
Great work! I guess it'd make sense to add Flama to the "Frameworks" section of https://www.starlette.io/third-party-packages/ right?

**Comment by perdy** [comment]
Yup! This project is a reworking from Starlette API that is listed in that page but I forgot to update it 😅 

I'll make a PR to update the docs, thanks for reminder!

**Comment by perdy** [comment]
Done :)
