### ISSUE TITLE
AttributeError: 'MarshmallowPlugin' object has no attribute 'openapi'

### ISSUE THREAD

**Issue by dasouch** [perdy/flama#31]
AttributeError: 'MarshmallowPlugin' object has no attribute 'openapi'

apispec==3.1.0
flama==0.11.0
marshmallow==3.3.0
starlette==0.12.13
uvicorn==0.10.8
uvloop==0.14.0

**Comment by perdy** [comment]
Hi!

It seems caused by a backward incompatible change in [apispec 3.0.0](https://apispec.readthedocs.io/en/latest/changelog.html#id2).

Have you manually defined apispec as requirement for your project? Flama's requirements defined the apispec version with following constraints: `>=1.0, <2.0`.
