### ISSUE TITLE
Support / test newer versions of dependencies

### ISSUE THREAD

**Issue by uSpike** [perdy/flama#32]
Because the following version constraints are defined:

```
apispec = {version = "^1.0",optional = true}
pyyaml = {version = "^3.13",optional = true}
```

Only `apispec 1.x` and `pyyaml 3.13.x` will be used/tested when `flama[schema]` is installed.

`apispec` is on version 3 and `pyyaml` is at 5 now.  There are numerous useful changes in those projects that can be integrated into `flama`.

**Comment by perdy** [comment]
The new version of Flama (v0.12) now supports apispec 3 and pyyaml 5.

Thanks!
