### ISSUE TITLE
Branding: remove "with this flamethrower" tagline

### ISSUE THREAD

**Issue by davenquinn** [perdy/flama#35]
The branding/logo of this project is great and "Flama" is a nicer name than its FastAPI competitor. However, the "with this flamethrower" tagline is overly narrow. Why is an API like a flamethrower? Just ends up sounding weird.

I suggest you just make the tagline "Fire up your API". Simple.

**Comment by perdy** [comment]
The branding is a bit homemade and I'm far away of being an expert on this field so any help is really appreciated.

Thanks for your suggestion and contribution.
