### ISSUE TITLE
request syntax in flama

### ISSUE THREAD

**Issue by sugizo** [perdy/flama#41]
**objective** 
can have api from cli
**e.g.**
**request.headers['api_key']**
`curl -X GET -i http://localhost:8000/api/http_api_key/instrument/ -H 'api_key: stifix'`
**request.query_params**
`curl -X PUT -i "http://localhost:8000/api/put/instrument/2?name=name0&strings=0"`
**request.form()**
`curl -X PUT -d "name=name1&strings=1" -i http://localhost:8000/api/put/instrument/2`
**request.json()**
`curl -X PUT -d '{"name": "name2", "strings": 2}' -i http://localhost:8000/api/put_json/instrument/2`

in starlette we can use request 
**e.g.**
```
def test(request):
    request.headers['api_key']
    request.query_params
    request.form()
    request.json()
```

since flama is base on starlette, what is equivalent of starlette request above ?

thanks

**Comment by perdy** [comment]
You can just inject the dependency into the function:

```python
from flama.http import Request


def test(request: Request):
    request.headers["api_key"]
    request.query_params
    request.form()
    request.json()
```
