### ISSUE TITLE
marshmallow 3.0.0rc4 is not stable ?

### ISSUE THREAD

**Issue by matrixise** [perdy/flama#9]
Sorry, but I can't fix one issue because there is an issue with the dependencies and I don't know why.

1. when I use `poetry install` for the installation of the dependencies, it tries to install marshmallow 3.0.0rc4, but in the `pyproject.toml` file, it's `2.19.0`.
But this is not the case in the `poetry.lock` file.

and because I don't know `poetry` I have to learn the project and try to fix the issue with the dependency.
Which version of `marshmallow` do you want to use? 3.0.0rc4 or 2.19.0 ?

Thanks you

**Comment by PeRDy** [comment]
It's intended to use a version 3 of marshmallow, the changed some parts of the API that make me hard to integrate version 2 with Starlette API and version 3 is pretty stable right now, I've been using it in production for several months without any issue.

I just checked that repository and your fork (both in master branch) and `pyproject.toml` isn't specifying marshmallow `2.19.0`, in fact it requires a version greater than 2 and allowing prereleases that should currently points to a `3.0.0-rc`. Also it's the same for `poetry.lock`, that specifies `3.0.0rc4`.

**Comment by matrixise** [comment]
ok, I am going to retest
